# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test_field',
            field=models.CharField(default='', max_length=200),
        ),
    ]
